services:
  app:
    image: carlescanals/centre-educatiu:latest
    container_name: laravel_app
    ports:
      - "8001:8000"  # Mapeja el port extern 8001 al port intern 8000
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    ports:
      - "3307:3306"   # Mapeja el port extern 3307 al port intern 3306
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8002:80"   # Mapeja el port extern 8002 al port intern 80
    depends_on:
      - db

volumes:
  db_data:
    driver: local
