name: Deploy to Docker Hub and remote server

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: carlescanals/centre-educatiu:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: SSH into remote server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 139.59.169.177
          username: root
          password: "XD3r&RBP@8ng"
          script: |
            # 1. Docker login a Docker Hub
            docker login -u carlescanals -p ${{ secrets.DOCKERHUB_PASSWORD }}
            
            # 2. Pull de la imatge més recent
            docker pull carlescanals/centre-educatiu:latest
            
            # 3. Crear/actualitzar docker-compose.prod.yml (o copiar-lo des del repo)
            #    Pots clonar el repo o copiar-lo, o tenir-lo al servidor ja
            #    Aquí suposo que ja tens el docker-compose.prod.yml al servidor.

            # 4. Anar al directori on tens docker-compose.prod.yml
            cd /home/carles/home

            # 5. Aturar contenidors antics i aixecar els nous
            docker-compose -f docker-compose.prod.yml down
            docker-compose -f docker-compose.prod.yml up -d
